# Generated by Django 3.0.3 on 2022-06-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220531_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedMovie',
            new_name='FavoriteMovie',
        ),
    ]
