# Generated by Django 4.0.4 on 2022-06-01 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_favoritemovie_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemovie',
            old_name='searchType',
            new_name='search_type',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favoriteColor',
            new_name='favorite_color',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_city',
            field=models.CharField(default='Houston', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
