# Generated by Django 4.0.4 on 2022-06-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='search_type',
            field=models.CharField(choices=[('FN', 'First Name'), ('LN', 'Last Name'), ('BD', 'Birthday'), ('FC', 'Favorite Color'), ('SW', 'Search Word')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_color',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
