# Generated by Django 4.0.4 on 2022-06-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_favoritemovie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemovie',
            old_name='user',
            new_name='user_id',
        ),
    ]
