# Generated by Django 4.0.4 on 2022-06-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_favoritemovie_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='user_id',
        ),
    ]
