# Generated by Django 4.0.4 on 2022-06-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_favoritemovie_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
            preserve_default=False,
        ),
    ]
