# Generated by Django 4.0.4 on 2022-06-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
