# Generated by Django 3.0.3 on 2022-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220601_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='search_type',
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
